<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Life.Domain\Life.Domain.csproj" />
    <ProjectReference Include="..\Life.Infrastructure\Life.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Commons\Models\" />
    <Folder Include="UseCases\Homeworks\GetHomework\" />
    <Folder Include="UseCases\Homeworks\DeleteHomework\" />
    <Folder Include="UseCases\Homeworks\UpdateHomework\" />
  </ItemGroup>

</Project>
